version: '3'

services:
  web:
    image: nginx:1.21-alpine
    restart: always
    container_name: hello-todos
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.niklist_nikstack_de.rule=Host(`niklist.nikstack.de`)'
      - 'traefik.http.routers.niklist_nikstack_de.entrypoints=web,websecure'
      - 'traefik.http.services.niklist_nikstack_de.loadbalancer.server.port=80'
networks:
  traefik:
    external: true
